import { motion, AnimatePresence } from 'framer-motion';
import { useState } from 'react';

interface LearningPathProps {
  learningPath: {
    id: string;
    title: string;
    description: string;
    status: 'completed' | 'in-progress' | 'upcoming';
    progress?: number;
    completedOn?: string;
    topics: string[];
    isAiGenerated?: boolean; // New prop to indicate dynamically inserted modules
  }[];
}

export default function LearningPath({ learningPath }: LearningPathProps) {
  const [expandedNode, setExpandedNode] = useState<string | null>(null);

  if (!learningPath) return null;

  return (
    <div className="mb-8 relative z-10">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h2 className="text-2xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-emerald-400">
            Adaptive Curriculum Timeline
          </h2>
          <p className="text-sm text-slate-400 mt-1">Dynamically generated by your Orchestrator Agent</p>
        </div>
        <a href="#path" className="text-blue-400 flex items-center hover:text-blue-300 transition-colors">
          View full map
          <span className="material-icons text-sm ml-1">bubble_chart</span>
        </a>
      </div>
      
      <div className="p-8 rounded-2xl glassmorphism-dark relative overflow-hidden glow-border">
        {/* Abstract background elements */}
        <div className="absolute top-0 right-0 w-64 h-64 bg-blue-500/10 rounded-full blur-3xl -z-10 animate-pulse" />
        <div className="absolute bottom-0 left-0 w-64 h-64 bg-emerald-500/10 rounded-full blur-3xl -z-10 animate-pulse" style={{ animationDelay: '2s' }} />

        <div className="relative">
          {/* Animated vertical line */}
          <div className="absolute top-0 bottom-0 left-[22px] w-1 bg-slate-800 rounded-full overflow-hidden">
             <motion.div 
               initial={{ height: 0 }}
               animate={{ height: "100%" }}
               transition={{ duration: 2, ease: "easeInOut" }}
               className="w-full bg-gradient-to-b from-blue-500 via-emerald-500 to-slate-800"
             />
          </div>
          
          {learningPath.map((item, index) => {
            const isCompleted = item.status === 'completed';
            const isInProgress = item.status === 'in-progress';
            const isGenerated = item.isAiGenerated || index % 3 === 2; // Demo: Every 3rd item is marked AI generated

            return (
              <motion.div 
                key={item.id}
                initial={{ opacity: 0, x: -50 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ duration: 0.5, delay: index * 0.2 }}
                className={`relative flex items-start group ${index !== learningPath.length - 1 ? 'mb-12' : ''}`}
              >
                {/* Node Dot */}
                <div className={`absolute top-0 left-[11px] h-6 w-6 rounded-full flex items-center justify-center z-10 
                  ${isCompleted || isInProgress ? 'bg-slate-900 border-2 border-blue-500 shadow-[0_0_15px_rgba(59,130,246,0.5)]' : 'bg-slate-900 border-2 border-slate-600'}
                  transition-all duration-300 group-hover:scale-125
                `}>
                  {(isCompleted || isInProgress) && (
                    <div className="h-2 w-2 rounded-full bg-blue-400 animate-ping" />
                  )}
                </div>

                {/* AI Insertion Indicator */}
                {isGenerated && (
                  <motion.div 
                    initial={{ opacity: 0, scale: 0 }}
                    animate={{ opacity: 1, scale: 1 }}
                    transition={{ delay: index * 0.2 + 0.5 }}
                    className="absolute top-1 -left-4 w-3 h-3 bg-purple-500 rounded-full shadow-[0_0_10px_rgba(168,85,247,0.8)] z-20 cursor-help"
                    title="Orchestrator Agent inserted this module based on your current persona."
                  />
                )}

                <div className="ml-14 w-full">
                  <motion.div 
                    layout
                    onClick={() => setExpandedNode(expandedNode === item.id ? null : item.id)}
                    className={`cursor-pointer border border-white/5 rounded-xl p-5 transition-all duration-300
                      ${expandedNode === item.id ? 'bg-slate-900/40 glassmorphism/10 shadow-lg border-white/20' : 'bg-slate-900/40 glassmorphism/5 hover:bg-slate-900/40 glassmorphism/10'}
                      ${isInProgress ? 'ring-1 ring-blue-500/50' : ''}
                    `}
                  >
                    <div className="flex flex-col md:flex-row md:items-center justify-between mb-2">
                      <div className="flex items-center space-x-3">
                        <h3 className="font-bold text-lg text-white">{item.title}</h3>
                        {isGenerated && (
                          <span className="px-2 py-0.5 text-[10px] uppercase tracking-wider font-bold rounded bg-purple-500/20 text-purple-300 border border-purple-500/30">
                            AI Adapted
                          </span>
                        )}
                      </div>
                      <span className={`px-3 py-1 text-xs font-semibold rounded-full tracking-wide shadow-2xl mt-2 md:mt-0 w-max
                        ${isCompleted ? 'bg-emerald-500/20 text-emerald-300 border border-emerald-500/30' : 
                          isInProgress ? 'bg-blue-500/20 text-blue-300 border border-blue-500/30' : 
                          'bg-slate-800 text-slate-400 border border-slate-700'}
                      `}>
                        {isCompleted ? 'Completed' : isInProgress ? 'In Progress' : 'Locked'}
                      </span>
                    </div>

                    <p className="text-sm text-slate-300 mb-4">{item.description}</p>
                    
                    <div className="flex flex-wrap gap-2 mb-2">
                      {item.topics.map((topic, idx) => (
                        <span key={idx} className="px-2.5 py-1 text-xs rounded-md bg-black/30 border border-white/5 text-slate-300">
                          {topic}
                        </span>
                      ))}
                    </div>

                    <AnimatePresence>
                      {expandedNode === item.id && (
                        <motion.div
                          initial={{ opacity: 0, height: 0 }}
                          animate={{ opacity: 1, height: 'auto' }}
                          exit={{ opacity: 0, height: 0 }}
                          className="overflow-hidden"
                        >
                          <div className="pt-4 mt-4 border-t border-white/10">
                            {isCompleted && item.completedOn && (
                              <div className="flex items-center text-sm text-emerald-400">
                                <span className="material-icons text-sm mr-2">verified</span>
                                <span>Mastery achieved on {item.completedOn}</span>
                              </div>
                            )}
                            
                            {isInProgress && typeof item.progress === 'number' && (
                              <div className="mt-2">
                                <div className="flex justify-between text-sm text-blue-300 mb-2 font-medium">
                                  <span>Current Status</span>
                                  <span>{item.progress}% to Mastery</span>
                                </div>
                                <div className="w-full bg-slate-900 rounded-full h-2.5 shadow-inner">
                                  <motion.div 
                                    initial={{ width: 0 }} animate={{ width: `${item.progress}%` }} transition={{ duration: 1 }}
                                    className="bg-gradient-to-r from-blue-400 to-emerald-400 h-2.5 rounded-full" 
                                  />
                                </div>
                                <button className="mt-4 w-full py-2.5 bg-blue-600 hover:bg-blue-500 text-white font-medium rounded-lg transition-colors flex items-center justify-center shadow-lg shadow-blue-900/20">
                                  <span className="material-icons text-sm mr-2">play_arrow</span>
                                  Resume Learning
                                </button>
                              </div>
                            )}
                            
                            {item.status === 'upcoming' && (
                              <div className="flex items-center p-3 rounded-lg bg-slate-900/50 border border-slate-800 text-slate-400 text-sm">
                                <span className="material-icons text-sm mr-2">lock_outline</span>
                                Please demonstrate mastery in prerequisites to unlock.
                              </div>
                            )}
                          </div>
                        </motion.div>
                      )}
                    </AnimatePresence>
                  </motion.div>
                </div>
              </motion.div>
            );
          })}
        </div>
      </div>
    </div>
  );
}
